Feature/order generation
KarmaKamikaze/FCDS pull request #104
Opened 2021-04-13 13:07 UTC by mirakst

Hej gutter
pls review
🥶

2021-04-13 13:22 UTC, AndersMariegaard commented on node/PublicResources/js/aStar.js
> -
Hvad har det her mellemrum gjort?

2021-04-13 13:40 UTC, AndersMariegaard commented on node/PublicResources/js/orderGeneration.js
> +  this.hasAllergens = Math.random() > 0.95;
specifikt til knapsack

2021-04-13 13:54 UTC, AndersMariegaard approved these changes

2021-04-13 13:59 UTC, Sarmisuper requested changes
Nice, har langt en enkelt comment som der lige skal ændres noget småt ved. Så har jeg også lagt en anden comment fordi jeg ikke helt forstår hvad der sker der

2021-04-13 13:59 UTC, Sarmisuper commented on node/PublicResources/js/graphHelper.js
> +    for (let i = 0; i <= path.length - 2; i++) {
Kan i forklare mig hvorfor det er path.length-2?

2021-04-13 13:59 UTC, Sarmisuper commented on node/PublicResources/js/orderGeneration.js
> +function startSimulation(cyGraph, tickSpeed) {
doxygen kommentaren mangler "tickspeed" parameteren

2021-04-13 14:01 UTC, KasperHenningsen approved these changes

2021-04-13 14:19 UTC, KarmaKamikaze reviewed
Det ser rigtig godt ud, drenge! Der er virkelig nogle smarte ting heri. Jeg har lige et par kommentarer som i kan overveje.

2021-04-13 14:19 UTC, KarmaKamikaze commented on node/PublicResources/js/graphHelper.js
> +        couriers: new Array(),
Er dette array for at se, hvor mange couriers der i fremtiden er tildelt en idle zone?

2021-04-13 14:19 UTC, KarmaKamikaze commented on node/PublicResources/js/graphHelper.js
> +        //inRoute: new Array(),
Skal de her to comments slettes?

2021-04-13 14:19 UTC, KarmaKamikaze commented on node/PublicResources/js/graphCore.js
>  import { aStar } from "./aStar.js";
Hvis SPAs ikke bliver brugt herinde mere, så bare nak dem.

2021-04-13 14:19 UTC, KarmaKamikaze commented on node/PublicResources/js/orderGeneration.js
> +function printTime(timeMinutes) {
Måske et andet navn ville være nice. Den printer nemlig ingenting.

2021-04-13 14:19 UTC, KarmaKamikaze commented on node/PublicResources/js/orderGeneration.js
> +function Order(id, origin, destination, startTime) {
Skal det ikke være en class?

2021-04-13 14:19 UTC, KarmaKamikaze commented on node/PublicResources/js/graphCore.js
>  import { aStar } from "./aStar.js";
Nevermind, I can't read code.

2021-04-14 07:39 UTC, mirakst commented on node/PublicResources/js/orderGeneration.js
> +function Order(id, origin, destination, startTime) {
Det synes jeg ikke - det er jo bare en constructor funktion uden methods 😄

2021-04-14 07:46 UTC, mirakst commented on node/PublicResources/js/graphHelper.js
> +    for (let i = 0; i <= path.length - 2; i++) {
Fordi der stod <=, men det er nu ændret til < og - 1 for clarity.
For the greater good!

2021-04-14 07:47 UTC, mirakst commented on node/PublicResources/js/graphHelper.js
> +        couriers: new Array(),
Ja, men generelt bare for at se de couriers der befinder sig på en node

2021-04-14 07:49 UTC, AndersMariegaard approved these changes

2021-04-14 07:58 UTC, merged