Feature/statsfunction
KarmaKamikaze/FCDS pull request #110
Opened 2021-04-21 11:40 UTC by Sarmisuper

tilføjet et stats objekt til hver cygraph, der opdateres når det er relevant. Derudover har vi ryddet æidt op i guess. avg. del. time virker men det er lidt wonky da værdien kan blive påvirket, hvis simulationen lagger. Der er dog ikke så meget der kan gøres ved det... Derudover har vi snakket lidt om at couriersne måske er liiiiiidt for hurtige, men vi har også kun testen det på de mindre netværk.

2021-04-21 11:42 UTC, Sarmisuper commented on node/PublicResources/js/orderGeneration.js
> +  cyGraph.simulationStats.simTime = formatTime(timeMinutes);
Disse to kommandoer can placeres i nedenstående if-statement, 
    hvis det ikke ønskes at bruge for meget computational time. 
    De er dog placeret her, da couriersne er så fucking hurtige at 
    de når det under 5 min. Derfor så tror koden nogle gange at start- og endtime 
    er det samme. Altså at courieren bruger 0 min på at hente ordren og deliver.

2021-04-21 12:12 UTC, SimonPRasmussen requested changes
It's lit 🔥
Det ser godt ud, jeg har nogle få bemærknigner og spørgsmål - samt det med tilføjelsen af et array af active orders - ellers er det 👌

2021-04-21 12:12 UTC, SimonPRasmussen commented on node/PublicResources/js/stats.js
> +  this.failedOrders = 0;
Burder der også være en indikator på hvor mange succesfully completed orders der er? Eller skal man selv udregne det ved at trække de failed ones fra finished ones?
Eller er det allerede angivet et andet sted jeg ikke har set? 🤔

2021-04-21 12:12 UTC, SimonPRasmussen commented on node/PublicResources/js/orderGeneration.js
> +        cyGraph.simulationStats.finishedOrders;
Ser godt ud (ligesom mig 😎). A question tho: indeholder 'finishedOrders' både dem der er successfully completed & failed?

2021-04-21 12:12 UTC, SimonPRasmussen commented on node/PublicResources/js/stats.js
> +  this.activeOrders = 0;
Som jeg forstår det, skal der være et felt der angiver de ordre der er i gang, udover blot antallet.
Jeg ved ikke om det skal inkludere her, men min umiddelbare indskydelse ville være at inkludere det heri, da informationerne om ordrene kan inkluderes på lignende vis som andre datafelter for 'simStats'.

2021-04-21 12:12 UTC, SimonPRasmussen commented on node/PublicResources/js/stats.js
> +  this.activeOrders = 0;
Lidt på lignende vis som det ser ud til i har gjort med arrayet for finished orders, som jeg lige forstår det.

2021-04-21 12:16 UTC, Sarmisuper commented on node/PublicResources/js/stats.js
> +  this.failedOrders = 0;
Den værdi ligger i finished orders

2021-04-21 12:18 UTC, Sarmisuper commented on node/PublicResources/js/orderGeneration.js
> +        cyGraph.simulationStats.finishedOrders;
Indtil videre er failed orders ikke implementeret endnu siden delivery time constraint ikke er implementeret. Så lige nu er alle orders succesfully completed. Jeg tænker at finishedorders kun skal indeholde de succesfully completed orders.

2021-04-21 12:19 UTC, AndersMariegaard commented on node/PublicResources/js/stats.js
> +  this.failedOrders = 0;
"succesfully completed orders" er finishedOrders, den totale mængde af ordrer er totalOrders. Pending er dem der venter på at blive sendt afsted, active er igang med deres rute og failed er dem der har stået for lang tid og gået tabt.

2021-04-21 12:21 UTC, AndersMariegaard commented on node/PublicResources/js/orderGeneration.js
> +        cyGraph.simulationStats.finishedOrders;
kun delivered, de failed er i failedOrders og den totale mængde er i totalOrders

2021-04-21 12:33 UTC, Sarmisuper commented on node/PublicResources/js/stats.js
> +  this.activeOrders = 0;
Som jeg har forstået det, så skal vi have et tekstfelt, der printer ordersne når de bliver generated. Altså så alle orders printes og man så kan skrulle op og se den første order. Der ville et active orders array ikke fungere, da de færdige orders så skal splices ud af arrayet

2021-04-22 10:44 UTC, SimonPRasmussen approved these changes
Looks good 👍🏿

2021-04-22 11:11 UTC, closed without merging