Feature/graph helper fixes
KarmaKamikaze/FCDS pull request #130
Opened 2021-04-29 12:57 UTC by damniko

Implemented:
- Graph radius & idle zone formula in heatGeneration.js
- Fixed headless traversal and couriers now use idle zones (if the setting is enabled)
- The 'find courier' function has been vastly improved 🗡️ 
- Added 'deliver order' function which tracks failed orders (and updates stats in general upon delivery)
- and many other super duper fixes

This closes #95

2021-04-29 14:24 UTC, Sarmisuper requested changes
Har reviewet det og lagt nogle comments, hvor der mangler noget ift at opdatere ordrer på headless simulation. Altså i forhold til status af en order og hvilken courier der har ordren. Lige nu som pull requesten er så mangler de ting, og derfor har jeg skrevet at linjerne mangler. De kan bare kopieres og puttes ind der hvor det er relevant. Det kan gøres på en anden måde, men det er bare lettere, hvis alt informationen ligger i orders objektet istedet for fx courier objektet.

Derudover har jeg lagt comments hvor i har console logs. Nogle af dem er kommenteret ud, andre er ikke. Jeg har bare lagt comments for at gøre jer opmærksomme på at de er der, hvis i nu havde overset dem og glemt at slette dem. 

Ellers ser det lækkert ud. Godt arbejde

2021-04-29 14:24 UTC, Sarmisuper commented on node/PublicResources/js/graphHelper.js
> +    //console.log(`placed ${courier.id()} at node ${randomNode.id()}`)
fjern commenten

2021-04-29 14:24 UTC, Sarmisuper commented on node/PublicResources/js/graphHelper.js
> +      // console.log(`${courier.id()}: nvm bro`)
delete this

2021-04-29 14:24 UTC, Sarmisuper commented on node/PublicResources/js/graphHelper.js
> +      courier.data("moving", false);
Er ikke helt sikker på jeg forstår det her. er .data("pendingOrder") en boolean der er true hvis en courier leder efter en order?

2021-04-29 14:24 UTC, Sarmisuper commented on node/PublicResources/js/graphHelper.js
> +            //console.info(this.timeMinutes-order.startTime);
delete

2021-04-29 14:24 UTC, Sarmisuper commented on node/PublicResources/js/graphHelper.js
> -    order.status = "transit";
Denne linje mangler i koden

2021-04-29 14:24 UTC, Sarmisuper commented on node/PublicResources/js/graphHelper.js
> +      //console.log(`Moving ${courier.id()} to idle zone ${bestZone.id()}`);
delete

2021-04-29 14:24 UTC, Sarmisuper commented on node/PublicResources/js/graphHelper.js
> +          console.log(`${courier.id()}: nvm bro`)
this console log?

2021-04-29 14:24 UTC, Sarmisuper commented on node/PublicResources/js/graphHelper.js
> -          order.status = "delivered";
denne linje mangler i deliverOrder funktionen

2021-04-29 14:24 UTC, Sarmisuper commented on node/PublicResources/js/graphHelper.js
> +        console.log(`Oh no, order${order.id} took ${order.deliveryTime} minutes! Anyway...`);
These console logs tho

2021-04-29 14:24 UTC, Sarmisuper commented on node/PublicResources/js/graphHelper.js
> +      //console.log(`${courier.id()} has delivered their order and is heading home. Bye!`);
delete this

2021-04-29 14:24 UTC, Sarmisuper commented on node/PublicResources/js/orderGeneration.js
> +  // The expectedCouriers array denotes how many couriers should be available at each hour of the day (starting at 00:00)
Denne comment passer ikke heeeelt til hvad der står i koden. "The expectedCouriers array" er vel forkert

2021-04-29 14:24 UTC, Sarmisuper commented on node/PublicResources/js/orderGeneration.js
> +    // console.log(`[${courier.id()}] ${order.restaurant.id()} -> ${order.customer.id()}`)
delete?

2021-04-29 14:24 UTC, Sarmisuper commented on node/PublicResources/js/orderGeneration.js
> -    order.assignedCourier = courier.id(); /* Used to print the assigned courier of an order only using an array of orders*/
denne linje mangler i koden

2021-04-29 14:40 UTC, AndersMariegaard commented on node/PublicResources/js/orderGeneration.js
> +    if (i < Math.ceil(n/2)) {
magiske tal?

2021-04-29 14:41 UTC, AndersMariegaard commented on node/PublicResources/js/orderGeneration.js
> +    console.log(`[${cyGraph.name}] Day ${cyGraph.simulationStats.simDays}: Succesful orders: ${cyGraph.simulationStats.deliveredOrdersArr.length - cyGraph.simulationStats.failedOrders}/${cyGraph.simu
kunne måske godt bruge noget formattering

2021-05-05 09:08 UTC, damniko commented on node/PublicResources/js/graphHelper.js
> -          order.status = "delivered";
done john

2021-05-05 09:09 UTC, damniko commented on node/PublicResources/js/orderGeneration.js
> +  // The expectedCouriers array denotes how many couriers should be available at each hour of the day (starting at 00:00)
fixed yo

2021-05-05 09:09 UTC, damniko commented on node/PublicResources/js/orderGeneration.js
> -    order.assignedCourier = courier.id(); /* Used to print the assigned courier of an order only using an array of orders*/
den er tilføjet homes

2021-05-05 09:17 UTC, Sarmisuper approved these changes

2021-05-05 09:17 UTC, merged